package com.danasea.backend.modules.ai.application.port;

import com.danasea.backend.modules.ai.domain.models.AiMessage;
import com.danasea.backend.modules.ai.domain.models.LlmResponse;

import java.util.List;
import com.danasea.backend.shared.i18n.SupportedLanguage;

public interface LlmClientPort {
    /**
     * Generates a response from the LLM based on the conversation history.
     * 
     * @param messages The list of AI messages forming the conversation
     * @return The response object generated by the LLM (content or tool calls)
     */
    LlmResponse generateResponse(List<AiMessage> messages);

    default LlmResponse generateResponse(List<AiMessage> messages, SupportedLanguage language) {
        return generateResponse(messages);
    }
}
