/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: { "surface-container-highest": "#dee3e4", "on-tertiary-container": "#f4fbff", "secondary-container": "#fb7059", "on-tertiary-fixed-variant": "#2e4b56", "on-error-container": "#93000a", "primary-fixed-dim": "#79d4e2", "primary-container": "#087f8c", "secondary": "#aa3524", "surface-container-lowest": "#ffffff", "surface-container": "#eaeff0", "tertiary-fixed": "#c9e7f6", "on-primary": "#ffffff", "outline": "#6e797b", "tertiary": "#425e6a", "surface-tint": "#006874", "inverse-surface": "#2c3132", "surface-bright": "#f5fafb", "on-primary-container": "#effdff", "on-error": "#ffffff", "on-background": "#171d1e", "tertiary-fixed-dim": "#adcbd9", "on-secondary-fixed-variant": "#891d0f", "surface-variant": "#dee3e4", "on-surface-variant": "#3e494a", "inverse-primary": "#79d4e2", "surface-container-high": "#e4e9ea", "background": "#f5fafb", "inverse-on-surface": "#edf2f3", "error-container": "#ffdad6", "surface-container-low": "#eff4f5", "on-tertiary-fixed": "#001f29", "primary": "#00646f", "secondary-fixed-dim": "#ffb4a7", "on-primary-fixed-variant": "#004f57", "on-surface": "#171d1e", "on-tertiary": "#ffffff", "surface": "#f5fafb", "on-secondary": "#ffffff", "error": "#ba1a1a", "on-secondary-container": "#6c0600", "primary-fixed": "#95f1ff", "secondary-fixed": "#ffdad4", "tertiary-container": "#5a7784", "outline-variant": "#bdc9ca", "on-secondary-fixed": "#400200", "on-primary-fixed": "#001f24", "surface-dim": "#d6dbdc" },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
      spacing: { "space-md": "1rem", "space-sm": "0.5rem", "margin": "5rem", "space-xs": "0.25rem", "space-lg": "1.5rem", "space-2xl": "3rem", "margin-sm": "1.5rem", "space-xl": "2rem", "space-3xl": "4.5rem", "gutter": "1.5rem", "gutter-lg": "2rem", "gutter-sm": "1rem", "margin-md": "3rem" },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        heading: ["Inter", "sans-serif"],
        outfit: ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["36px", { "lineHeight": "44px", "fontWeight": "700" }],
        "display-xl": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-lg": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "headline-xl": ["26px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-lg": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-sm": ["17px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-xl": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
      }
    },
  },
  plugins: [],
}
